const fs = require('fs');
const path = require('path');

const dictionary = JSON.parse(fs.readFileSync(path.resolve('src/dictionary.json'), 'utf-8'));
const overrides = JSON.parse(fs.readFileSync(path.resolve('src/dictionary-overrides.json'), 'utf-8'));
const source = fs.readFileSync(path.resolve('src/translit.js'), 'utf-8');

let output = source
  .replace(
    `const dictionary = require('./dictionary.json');`,
    `const dictionary = ${JSON.stringify(dictionary, null, 2)};`
  )
  .replace(
    `const dictionaryOverrides = require('./dictionary-overrides.json');`,
    `const dictionaryOverrides = ${JSON.stringify(overrides, null, 2)};`
  );

const exportMatch = output.match(/module\.exports\s*=\s*\{([\s\S]*?)\};/);
if (exportMatch) {
  const names = exportMatch[1].split(',').map(s => s.trim()).filter(Boolean);
  const exportStmts = names.map(n => `export { ${n} };`).join('\n');
  output = output.replace(exportMatch[0], exportStmts);
}

output = `// Auto-generated by scripts/build-browser.js — do not edit directly
${output}`;

fs.mkdirSync('dist', { recursive: true });
fs.writeFileSync('dist/translit.browser.mjs', output, 'utf-8');
console.log('Wrote dist/translit.browser.mjs');
